# Generated by Django 6.1 on 2026-08-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_organizationpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, help_text='Describe what the organization does. This information is provided to SHVYA AI as context.')),
                ('bot_languages', models.CharField(blank=True, help_text='Languages SHVYA AI can use when communicating with leads. Example: English, Hindi, Hinglish.', max_length=500)),
                ('qualification_requirements', models.TextField(blank=True, help_text='Instructions and requirements SHVYA AI should use when qualifying leads.')),
                ('ai_enabled', models.BooleanField(default=True, help_text='Master switch controlling whether SHVYA AI can operate for this organization.')),
                ('bump_up_enabled', models.BooleanField(default=True, help_text='Allow SHVYA AI to send bump-up messages to leads who have not responded.')),
                ('bump_up_count', models.PositiveIntegerField(default=2, help_text='Maximum number of bump-up messages that may be sent to a lead.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_info', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization AI Info',
                'verbose_name_plural': 'Organization AI Info',
                'ordering': ['-updated_at'],
            },
        ),
    ]
