# Generated by Django 6.1 on 2026-08-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0004_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='ai_knowledge/%Y/%m/'),
        ),
    ]
