# Generated by Django 6.1 on 2026-08-30 21:58

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0005_document_source_url_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='embedding_id',
        ),
        migrations.AddField(
            model_name='chunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
