# Generated by Django 6.1 on 2026-08-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0006_remove_chunk_embedding_id_chunk_embedding'),
        ('organizations', '0004_organizationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_key',
            field=models.CharField(blank=True, help_text='Stable identifier for the logical knowledge source. For URLs this is normally the normalized URL. For uploaded files this can be the logical file/source name.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'source_key', 'is_active'], name='ai_doc_source_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('organization', 'source_key', 'version'), name='uniq_org_document_source_version'),
        ),
    ]
