# Generated by Django 6.1 on 2026-08-30 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0007_document_source_key_document_version_and_more'),
        ('crm', '0015_stage_description'),
        ('organizations', '0004_organizationpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('source_message_count', models.PositiveIntegerField(default=0, help_text='Number of conversation messages considered when this summary was generated.')),
                ('generated_by', models.CharField(default='shvya_ai', help_text='Identifier for the component/provider that generated the summary.', max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='AI model used to generate this summary.', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this is the currently published summary for the lead.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_conversation_summaries', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_conversation_summaries', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_conversation_summaries', to='organizations.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['organization', 'lead', 'is_active'], name='ai_ics_org_lead_active_idx'), models.Index(fields=['lead', '-generated_at'], name='ai_ics_lead_generated_idx')],
            },
        ),
    ]
