# Generated by Django 6.1 on 2026-08-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0008_internalconversationsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalconversationsummary',
            name='source_last_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
