# Generated by Django 6.1 on 2026-08-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0009_internalconversationsummary_source_last_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalconversationsummary',
            name='source_last_message_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the latest conversation message included in this summary.', null=True),
        ),
        migrations.AlterField(
            model_name='internalconversationsummary',
            name='source_last_message_id',
            field=models.UUIDField(blank=True, help_text='ID of the latest conversation message included in this summary.', null=True),
        ),
    ]
