# Generated by Django 6.1 on 2026-09-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0011_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='engagement_instructions',
            field=models.TextField(blank=True, help_text='Instructions SHVYA AI should follow when engaging with leads in customer-facing conversations.'),
        ),
    ]
