# Generated by Django 6.1 on 2026-09-18 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0015_aitrace'),
        ('crm', '0024_repair_lead_pipeline_stage_consistency'),
        ('organizations', '0004_organizationpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_message_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=64)),
                ('action_type', models.CharField(max_length=32)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_receipts', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_receipts', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'lead', 'source_message_id'], name='ai_action_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'lead', 'idempotency_key'), name='uniq_ai_action_receipt')],
            },
        ),
    ]
