# Generated by Django 6.1 on 2026-09-18 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0016_aiactionreceipt'),
        ('crm', '0024_repair_lead_pipeline_stage_consistency'),
        ('organizations', '0004_organizationpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_message_id', models.UUIDField()),
                ('kind', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_signals', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_lead_signals', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'lead', 'kind'], name='ai_lead_signal_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'lead', 'source_message_id', 'kind', 'detail'), name='uniq_ai_lead_signal')],
            },
        ),
    ]
