import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="salesdocument",
            name="layout_override",
            field=models.TextField(
                blank=True,
                help_text="Optional sanitized per-document layout overriding the selected template.",
            ),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="pdf_file",
            field=models.FileField(blank=True, max_length=400, upload_to="sales/pdfs/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="pdf_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="revision_kind",
            field=models.CharField(
                choices=[
                    ("original", "Original"),
                    ("amendment", "Amendment"),
                    ("renewal", "Renewal"),
                ],
                default="original",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="revision_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="is_current_version",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="superseded_by",
                to="sales.salesdocument",
            ),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="first_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("signed", "Signed"),
                    ("unpaid", "Unpaid"),
                    ("partial", "Partially paid"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="tracking_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="first_clicked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="bounced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="open_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="bounce_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="SalesEmailTrackedLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("target_url", models.URLField(max_length=4096)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("first_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("delivery", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tracked_links", to="sales.salesdocumentdelivery")),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="SalesSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quotation_expiry_reminder_days", models.PositiveSmallIntegerField(default=3)),
                ("agreement_expiry_reminder_days", models.PositiveSmallIntegerField(default=7)),
                ("invoice_due_reminder_days", models.PositiveSmallIntegerField(default=3)),
                ("invoice_overdue_repeat_days", models.PositiveSmallIntegerField(default=3)),
                ("automatic_email_reminders", models.BooleanField(default=True)),
                ("attach_customer_files_to_email", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="sales_settings", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="SalesPaymentGateway",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(choices=[("razorpay", "Razorpay"), ("stripe", "Stripe")], max_length=20)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("public_key", models.CharField(blank=True, max_length=255)),
                ("encrypted_secret", models.TextField(blank=True)),
                ("encrypted_webhook_secret", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_payment_gateways", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="SalesActivity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("message", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_activity_events", to=settings.AUTH_USER_MODEL)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="sales.salesdocument")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_activities", to="organizations.organization")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SalesAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(max_length=400, upload_to="sales/attachments/%Y/%m/%d/")),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("visible_to_customer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="sales.salesdocument")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_attachments", to="organizations.organization")),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_attachments_uploaded", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SalesScheduledDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channels", models.JSONField(default=list)),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                ("whatsapp_body", models.TextField(blank=True)),
                ("base_url", models.URLField(blank=True, max_length=2048)),
                ("scheduled_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("completed", "Completed"), ("partial", "Partially completed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="pending", max_length=16)),
                ("error_message", models.TextField(blank=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_schedules_created", to=settings.AUTH_USER_MODEL)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scheduled_deliveries", to="sales.salesdocument")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_scheduled_deliveries", to="organizations.organization")),
            ],
            options={"ordering": ["scheduled_at", "created_at"]},
        ),
        migrations.CreateModel(
            name="SalesReminder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("quotation_expiry", "Quotation expiry"), ("agreement_expiry", "Agreement expiry"), ("invoice_due", "Invoice due"), ("invoice_overdue", "Invoice overdue")], max_length=32)),
                ("due_on", models.DateField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("skipped", "Skipped"), ("failed", "Failed")], default="pending", max_length=12)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminders", to="sales.salesdocument")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_reminders", to="organizations.organization")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SalesPaymentCheckout",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=8)),
                ("provider_reference", models.CharField(blank=True, max_length=255)),
                ("external_payment_id", models.CharField(blank=True, max_length=255)),
                ("checkout_url", models.URLField(blank=True, max_length=4096)),
                ("status", models.CharField(choices=[("created", "Created"), ("paid", "Paid"), ("expired", "Expired"), ("cancelled", "Cancelled"), ("failed", "Failed")], default="created", max_length=16)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_checkouts_created", to=settings.AUTH_USER_MODEL)),
                ("gateway", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="checkouts", to="sales.salespaymentgateway")),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payment_checkouts", to="sales.salesdocument")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_payment_checkouts", to="organizations.organization")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SalesPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("payment", "Payment"), ("refund", "Refund")], default="payment", max_length=10)),
                ("status", models.CharField(choices=[("succeeded", "Succeeded"), ("pending", "Pending"), ("failed", "Failed")], default="succeeded", max_length=12)),
                ("method", models.CharField(choices=[("cash", "Cash"), ("bank_transfer", "Bank transfer"), ("upi", "UPI"), ("card", "Card"), ("gateway", "Payment gateway"), ("other", "Other")], default="other", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=8)),
                ("payment_date", models.DateField()),
                ("reference_number", models.CharField(blank=True, max_length=160)),
                ("external_payment_id", models.CharField(blank=True, max_length=255)),
                ("provider", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("checkout", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payments", to="sales.salespaymentcheckout")),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="sales.salesdocument")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_payments", to="organizations.organization")),
                ("recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_payments_recorded", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-payment_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="SalesCreditNote",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("credit_number", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("applied", "Applied"), ("refunded", "Refunded"), ("cancelled", "Cancelled")], default="draft", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_credit_notes_created", to=settings.AUTH_USER_MODEL)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credit_notes", to="sales.salesdocument")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_credit_notes", to="organizations.organization")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SalesRecurringInvoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("interval_count", models.PositiveSmallIntegerField(default=1)),
                ("interval_unit", models.CharField(choices=[("day", "Day"), ("week", "Week"), ("month", "Month"), ("year", "Year")], max_length=8)),
                ("next_run_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("max_cycles", models.PositiveIntegerField(blank=True, null=True)),
                ("cycles_created", models.PositiveIntegerField(default=0)),
                ("auto_send_email", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sales_recurring_rules_created", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_recurring_invoices", to="organizations.organization")),
                ("source_invoice", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="recurring_rule", to="sales.salesdocument")),
            ],
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="scheduled_delivery",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deliveries", to="sales.salesscheduleddelivery"),
        ),
        migrations.AddField(
            model_name="salesdocumentdelivery",
            name="reminder",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deliveries", to="sales.salesreminder"),
        ),
        migrations.AddConstraint(
            model_name="salesdocumentdelivery",
            constraint=models.UniqueConstraint(condition=models.Q(scheduled_delivery__isnull=False), fields=("scheduled_delivery", "channel"), name="sales_delivery_schedule_channel_uniq"),
        ),
        migrations.AddConstraint(
            model_name="salesdocumentdelivery",
            constraint=models.UniqueConstraint(condition=models.Q(reminder__isnull=False), fields=("reminder", "channel"), name="sales_delivery_reminder_channel_uniq"),
        ),
        migrations.AddConstraint(
            model_name="salespaymentgateway",
            constraint=models.UniqueConstraint(fields=("organization", "provider"), name="sales_gateway_org_provider_uniq"),
        ),
        migrations.AddConstraint(
            model_name="salesreminder",
            constraint=models.UniqueConstraint(fields=("document", "kind", "due_on"), name="sales_reminder_doc_kind_due_uniq"),
        ),
        migrations.AddConstraint(
            model_name="salespayment",
            constraint=models.UniqueConstraint(condition=~models.Q(external_payment_id=""), fields=("organization", "provider", "external_payment_id", "kind"), name="sales_payment_provider_external_uniq"),
        ),
        migrations.AddConstraint(
            model_name="salescreditnote",
            constraint=models.UniqueConstraint(fields=("organization", "credit_number"), name="sales_credit_org_number_uniq"),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(fields=["organization", "document", "created_at"], name="sales_activity_doc_created"),
        ),
        migrations.AddIndex(
            model_name="salesactivity",
            index=models.Index(fields=["organization", "event_type", "created_at"], name="sales_activity_type_created"),
        ),
        migrations.AddIndex(
            model_name="salesattachment",
            index=models.Index(fields=["organization", "document", "created_at"], name="sales_attachment_doc_created"),
        ),
        migrations.AddIndex(
            model_name="salesscheduleddelivery",
            index=models.Index(fields=["status", "scheduled_at"], name="sales_schedule_due_idx"),
        ),
        migrations.AddIndex(
            model_name="salesscheduleddelivery",
            index=models.Index(fields=["organization", "status", "scheduled_at"], name="sales_schedule_org_due"),
        ),
        migrations.AddIndex(
            model_name="salespaymentcheckout",
            index=models.Index(fields=["organization", "invoice", "status"], name="sales_checkout_invoice_idx"),
        ),
        migrations.AddIndex(
            model_name="salesrecurringinvoice",
            index=models.Index(fields=["is_active", "next_run_at"], name="sales_recurring_due_idx"),
        ),
    ]
