# Generated by Django 6.1 on 2026-09-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespaymentcheckout',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='checkouts', to='sales.salespaymentgateway'),
        ),
    ]
