# Generated by Django 6.1 on 2026-08-15 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0002_alter_apikey_options_apikey_can_upsert_leads_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='uniq_org_email',
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'),  ('agent', 'Agent')], default='agent', max_length=20),
        ),
    ]
