# Generated by Django 6.1 on 2026-09-23 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_attributedefinition_is_active'),
        ('integrations', '0012_operationsconfigurationplan'),
        ('organizations', '0006_alter_organization_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticaccesslog',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_access_logs', to='organizations.apikey'),
        ),
        migrations.AlterField(
            model_name='diagnosticaccesslog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_access_logs', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='metaleadform',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meta_lead_forms', to='crm.pipeline'),
        ),
        migrations.AlterField(
            model_name='metaleadform',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meta_lead_forms', to='crm.stage'),
        ),
        migrations.AlterField(
            model_name='operationsauditevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_mcp_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationsauditevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_mcp_audit_events', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='operationsauditevent',
            name='support_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='integrations.operationssupportsession'),
        ),
        migrations.AlterField(
            model_name='operationsconfigurationplan',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operations_configuration_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operationsconfigurationplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_configuration_plans', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='operationsconfigurationplan',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='configuration_plans', to='integrations.operationsoauthtoken'),
        ),
    ]
