# Generated by Django 6.1 on 2026-09-23 10:19

from django.db import migrations, models


def preserve_audit_identifiers(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model("integrations", "OperationsAuditEvent").objects.using(alias).update(
        actor_reference=models.F("actor_id"), organization_reference=models.F("organization_id"),
    )
    apps.get_model("integrations", "DiagnosticAccessLog").objects.using(alias).update(
        organization_reference=models.F("organization_id"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_alter_diagnosticaccesslog_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticaccesslog',
            name='organization_reference',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='operationsauditevent',
            name='actor_reference',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='operationsauditevent',
            name='organization_reference',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(preserve_audit_identifiers, migrations.RunPython.noop),
    ]
