# Generated by Django 6.1 on 2026-09-23 20:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_diagnosticaccesslog_organization_reference_and_more'),
        ('organizations', '0007_organizationdeletioncleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsIntakeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('website', 'website'), ('brochures', 'brochures'), ('media', 'media'), ('offerings', 'offerings'), ('basics', 'basics'), ('faqs', 'faqs'), ('team', 'team'), ('qualification', 'qualification'), ('handoff', 'handoff'), ('blacklist', 'blacklist'), ('rules', 'rules'), ('proof', 'proof'), ('offers', 'offers'), ('scripts', 'scripts'), ('other', 'other')], max_length=24)),
                ('kind', models.CharField(choices=[('note', 'note'), ('question', 'question'), ('call', 'call'), ('attachment', 'attachment')], max_length=16)),
                ('external_id', models.CharField(max_length=120)),
                ('origin', models.CharField(choices=[('client_document', 'client_document'), ('call_export', 'call_export'), ('whatsapp_export', 'whatsapp_export'), ('ops_chat', 'ops_chat'), ('other', 'other')], max_length=24)),
                ('source_id', models.CharField(max_length=160)),
                ('source_ref', models.CharField(max_length=500)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reported', 'reported'), ('confirmed', 'confirmed'), ('conflict', 'conflict'), ('open', 'open'), ('answered', 'answered')], max_length=16)),
                ('body', models.TextField(validators=[django.core.validators.MaxLengthValidator(12000)])),
                ('is_active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('history', models.JSONField(blank=True, default=list, validators=[django.core.validators.MaxLengthValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_intake_entries', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['organization', 'is_active', 'id'], name='ops_intake_org_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'section', 'kind', 'external_id'), name='ops_intake_org_source_uniq'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='ops_intake_revision_positive')],
            },
        ),
    ]
