# Generated by Django 6.1.1 on 2026-10-04 20:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_instagram_phone_optional'),
        ('integrations', '0017_operations_commitments_acceptance'),
        ('organizations', '0007_organizationdeletioncleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaConversionsConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_id', models.CharField(blank=True, max_length=30)),
                ('encrypted_access_token', models.TextField(blank=True)),
                ('destination_version', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=True)),
                ('test_event_code', models.CharField(blank=True, max_length=100)),
                ('event_scope', models.CharField(choices=[('meta_leads', 'Meta Lead Ads only'), ('all_leads', 'All lead sources')], default='meta_leads', max_length=20)),
                ('user_data_fields', models.JSONField(blank=True, default=list)),
                ('custom_attribute_keys', models.JSONField(blank=True, default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta_conversions_configuration', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MetaConversionMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(default='Lead', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('action_source', models.CharField(default='system_generated', max_length=30)),
                ('value_source', models.CharField(choices=[('none', 'No value'), ('static', 'Static'), ('attribute', 'Attribute')], default='none', max_length=12)),
                ('static_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_attribute', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.stage')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.metaconversionsconfiguration')),
            ],
            options={
                'ordering': ['pipeline__name', 'stage__display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetaConversionDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=100)),
                ('dataset_id', models.CharField(max_length=30)),
                ('destination_version', models.UUIDField()),
                ('payload', models.JSONField(default=dict)),
                ('is_test', models.BooleanField(default=False)),
                ('is_probe', models.BooleanField(default=False)),
                ('test_event_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('retrying', 'Retrying'), ('sent', 'Accepted by Meta'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meta_error_code', models.PositiveIntegerField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('mapping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='integrations.metaconversionmapping')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.metaconversionsconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='metaconversionmapping',
            constraint=models.UniqueConstraint(fields=('configuration', 'stage'), name='uniq_meta_conversion_stage'),
        ),
        migrations.AddIndex(
            model_name='metaconversiondelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='meta_capi_delivery_due'),
        ),
        migrations.AddIndex(
            model_name='metaconversiondelivery',
            index=models.Index(fields=['organization', 'created_at'], name='meta_capi_org_created'),
        ),
        migrations.AddConstraint(
            model_name='metaconversiondelivery',
            constraint=models.UniqueConstraint(fields=('configuration', 'event_id'), name='uniq_meta_conversion_event'),
        ),
    ]
