# Generated by Django 6.1.1 on 2026-10-07 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engagement', '0022_channel_trace_parity'),
        ('integrations', '0020_indiamartconnection_indiamartreceipt'),
        ('organizations', '0007_organizationdeletioncleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsAIFlowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fixture_lead_id', models.UUIDField(editable=False)),
                ('fixture_account_id', models.UUIDField(editable=False)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('input_digest', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(default='whatsapp', max_length=30)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('max_turns', models.PositiveIntegerField(default=30)),
                ('max_provider_calls', models.PositiveIntegerField(default=100)),
                ('max_credits', models.PositiveIntegerField(default=1000)),
                ('provider_calls', models.PositiveIntegerField(default=0)),
                ('active_turn_id', models.UUIDField(editable=False, null=True)),
                ('configuration_digest', models.CharField(blank=True, max_length=64)),
                ('manifest', models.JSONField(default=dict, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleaned_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsAIFlowReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ai_engagement.aicreditreservation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_reservations', to='integrations.operationsaiflowrun')),
            ],
        ),
        migrations.CreateModel(
            name='OperationsAIFlowTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('input_digest', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('status', models.CharField(default='running', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='integrations.operationsaiflowrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='operationsaiflowrun',
            index=models.Index(fields=['organization', 'status'], name='ops_ai_flow_org_status'),
        ),
        migrations.AddConstraint(
            model_name='operationsaiflowrun',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='ops_ai_flow_run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='operationsaiflowturn',
            constraint=models.UniqueConstraint(fields=('run', 'idempotency_key'), name='ops_ai_flow_turn_idempotency'),
        ),
    ]
