from django.urls import path

from apps.followups.views.lead_control import lead_followup_control, lead_sequence_history
from apps.followups.views.web import (
    email_step_add,
    email_step_modal,
    lead_assign_sequence,
    lead_clear_sequence,
    lead_toggle_sequence,
    reminder_step_add,
    reminder_step_modal,
    sequence_create_page,
    sequence_create_save,
    sequence_delete,
    sequence_duplicate,
    sequence_edit_page,
    sequence_list,
    sequence_update_save,
    settings_modal,
    settings_save,
    step_delete_view,
    step_move,
    step_update,
    template_add,
    template_picker,
    template_preview,
)


urlpatterns = [
    path("sequences/", sequence_list, name="crm-auto-follow-ups-sequences"),
    path("sequences/new/", sequence_create_page, name="followups-sequence-create"),
    path("sequences/new/save/", sequence_create_save, name="followups-sequence-create-save"),
    path("sequences/<uuid:sequence_id>/", sequence_edit_page, name="followups-sequence-edit"),
    path("sequences/<uuid:sequence_id>/save/", sequence_update_save, name="followups-sequence-update"),
    path("sequences/<uuid:sequence_id>/duplicate/", sequence_duplicate, name="followups-sequence-duplicate"),
    path("sequences/<uuid:sequence_id>/delete/", sequence_delete, name="followups-sequence-delete"),
    path("sequences/<uuid:sequence_id>/templates/", template_picker, name="followups-template-picker"),
    path("sequences/<uuid:sequence_id>/templates/<uuid:template_id>/preview/", template_preview, name="followups-template-preview"),
    path("sequences/<uuid:sequence_id>/templates/add/", template_add, name="followups-template-add"),
    path("sequences/<uuid:sequence_id>/email/new/", email_step_modal, name="followups-email-step-modal"),
    path("sequences/<uuid:sequence_id>/email/add/", email_step_add, name="followups-email-step-add"),
    path("sequences/<uuid:sequence_id>/reminder/new/", reminder_step_modal, name="followups-reminder-step-modal"),
    path("sequences/<uuid:sequence_id>/reminder/add/", reminder_step_add, name="followups-reminder-step-add"),
    path("sequences/<uuid:sequence_id>/steps/<uuid:step_id>/save/", step_update, name="followups-step-update"),
    path("sequences/<uuid:sequence_id>/steps/<uuid:step_id>/delete/", step_delete_view, name="followups-step-delete"),
    path("sequences/<uuid:sequence_id>/steps/<uuid:step_id>/move/", step_move, name="followups-step-move"),
    path("settings/", settings_modal, name="followups-settings-modal"),
    path("settings/save/", settings_save, name="followups-settings-save"),
    path("leads/<uuid:lead_id>/control/", lead_followup_control, name="followups-lead-control"),
    path("leads/<uuid:lead_id>/history/", lead_sequence_history, name="followups-lead-history"),
    path("leads/<uuid:lead_id>/assign/", lead_assign_sequence, name="followups-lead-assign"),
    path("leads/<uuid:lead_id>/clear/", lead_clear_sequence, name="followups-lead-clear"),
    path("leads/<uuid:lead_id>/toggle/", lead_toggle_sequence, name="followups-lead-toggle"),
]
