# Generated by Django 6.1 on 2026-09-06 01:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("channels", "0010_whatsapptemplatemetadata_carousel_config"),
        ("crm", "0017_lead_ai_enabled"),
        ("organizations", "0004_organizationpayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("trigger_type", models.CharField(max_length=32)),
                ("conditions", models.JSONField(default=dict)),
                ("action_type", models.CharField(max_length=32)),
                ("action", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="TriggerEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=32)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TriggerRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_type", models.CharField(max_length=32)),
                ("action", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("detail", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="triggers.triggerevent",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="channels.whatsappmessage",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="triggers.smarttrigger",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="smarttrigger",
            index=models.Index(
                fields=["organization", "enabled", "trigger_type"],
                name="st_org_event_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="smarttrigger",
            constraint=models.UniqueConstraint(
                fields=("organization", "fingerprint"), name="st_org_fingerprint_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="triggerrun",
            index=models.Index(
                fields=["rule", "lead", "created_at"], name="st_cooldown_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="triggerrun",
            constraint=models.UniqueConstraint(
                fields=("rule", "event"), name="st_rule_event_unique"
            ),
        ),
    ]
