# Generated by Django 6.1 on 2026-09-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0010_whatsapptemplatemetadata_carousel_config"),
        ("crm", "0017_lead_ai_enabled"),
        ("organizations", "0004_organizationpayment"),
        ("triggers", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="triggerevent",
            index=models.Index(
                fields=["processed_at", "created_at"], name="st_pending_event_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="triggerevent",
            index=models.Index(
                fields=["lead", "kind", "created_at"], name="st_lead_clock_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="triggerrun",
            index=models.Index(fields=["status", "due_at"], name="st_due_run_idx"),
        ),
    ]
