from django.urls import path

from . import views_flat

urlpatterns = [
    path(
        "accounts/",
        views_flat.whatsapp_account_list_view,
        name="whatsapp-accounts",
    ),
    path(
        "connect/",
        views_flat.whatsapp_connect_choice_view,
        name="whatsapp-connect-choice",
    ),
    path(
        "connect/api/",
        views_flat.whatsapp_connect_api_view,
        name="whatsapp-connect-api",
    ),
    path(
        "connect/api/embedded-signup/",
        views_flat.whatsapp_embedded_signup_callback_view,
        name="whatsapp-embedded-signup-callback",
    ),
    path(
        "connect/hosted/",
        views_flat.whatsapp_connect_hosted_view,
        name="whatsapp-connect-hosted",
    ),
    path(
        "accounts/<uuid:account_id>/disconnect/",
        views_flat.whatsapp_disconnect_view,
        name="whatsapp-disconnect",
    ),
    path(
        "accounts/<uuid:account_id>/resubscribe/",
        views_flat.whatsapp_resubscribe_view,
        name="whatsapp-resubscribe",
    ),
    path(
        "send/<uuid:lead_id>/",
        views_flat.whatsapp_send_message_view,
        name="whatsapp-send-message",
    ),
    path(
        "campaigns/",
        views_flat.whatsapp_campaign_list_view,
        name="whatsapp-campaign-list",
    ),
    path(
        "campaigns/new/",
        views_flat.whatsapp_campaign_create_view,
        name="whatsapp-campaign-create",
    ),
    path(
        "campaigns/<uuid:campaign_id>/",
        views_flat.whatsapp_campaign_detail_view,
        name="whatsapp-campaign-detail",
    ),
    path(
        "campaigns/<uuid:campaign_id>/launch/",
        views_flat.whatsapp_campaign_launch_view,
        name="whatsapp-campaign-launch",
    ),
    path(
        "templates/",
        views_flat.whatsapp_template_list_view,
        name="whatsapp-template-list",
    ),
    path(
        "templates/new/",
        views_flat.whatsapp_template_create_view,
        name="whatsapp-template-create",
    ),
    path(
        "chats/",
        views_flat.whatsapp_chat_list_view,
        name="whatsapp-chats",
    ),
    path(
        "chats/<uuid:lead_id>/",
        views_flat.whatsapp_chat_detail_view,
        name="whatsapp-chat-detail",
    ),
]