# Generated by Django 6.1 on 2026-09-17 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0024_repair_lead_pipeline_stage_consistency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingBookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=32)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=16)),
                ('goal', models.TextField(max_length=1200)),
                ('interest', models.CharField(blank=True, max_length=140)),
                ('consent', models.BooleanField(default=False)),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_requests', to='crm.lead')),
            ],
            options={
                'verbose_name': 'BAC request',
                'verbose_name_plural': 'BAC requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
