import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models

import apps.shvya_calendar.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0029_alter_lead_lead_source_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarPage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("page_type", models.CharField(choices=[("lead", "Lead capture"), ("booking", "Booking"), ("lead_booking", "Lead capture + booking")], default="lead_booking", max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("disabled", "Disabled")], db_index=True, default="draft", max_length=20)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                ("language", models.CharField(default="en", max_length=12)),
                ("accent_color", models.CharField(default="#0060A2", max_length=16)),
                ("logo_url", models.URLField(blank=True)),
                ("intro_title", models.CharField(blank=True, max_length=120)),
                ("intro_description", models.TextField(blank=True)),
                ("intro_highlights", models.JSONField(blank=True, default=list)),
                ("form_schema", models.JSONField(blank=True, default=list)),
                ("submit_button_text", models.CharField(default="Continue to scheduling", max_length=80)),
                ("consent_enabled", models.BooleanField(default=True)),
                ("consent_text", models.CharField(default="I agree to be contacted regarding this booking.", max_length=300)),
                ("duplicate_behavior", models.CharField(choices=[("use_existing", "Use existing lead"), ("block", "Block duplicate submission")], default="use_existing", max_length=20)),
                ("duplicate_match_email", models.BooleanField(default=True)),
                ("lead_name_prefix", models.CharField(blank=True, max_length=60)),
                ("attribute_update_policy", models.CharField(choices=[("fill_blank", "Fill blank CRM values only"), ("overwrite", "Replace mapped CRM values"), ("submission_only", "Keep CRM values unchanged")], default="fill_blank", max_length=24)),
                ("notify_host_on_submission", models.BooleanField(default=True)),
                ("notify_user_ids", models.JSONField(blank=True, default=list)),
                ("notify_roles", models.JSONField(blank=True, default=list)),
                ("acknowledgement_enabled", models.BooleanField(default=False)),
                ("acknowledgement_subject", models.CharField(default="We received your request", max_length=180)),
                ("acknowledgement_body", models.TextField(default="Hi {{lead.name}},\n\nThanks for contacting {{organization.name}}. We have received your request.")),
                ("session_title", models.CharField(default="30-Minute Consultation Call", max_length=80)),
                ("session_description", models.CharField(blank=True, max_length=250)),
                ("discussion_points", models.JSONField(blank=True, default=list)),
                ("availability", models.JSONField(default=apps.shvya_calendar.models.default_availability)),
                ("bookable_days", models.PositiveSmallIntegerField(default=30)),
                ("minimum_notice_minutes", models.PositiveIntegerField(default=60)),
                ("slot_duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("max_slots_per_day", models.PositiveSmallIntegerField(default=25)),
                ("bookings_per_slot", models.PositiveSmallIntegerField(default=1)),
                ("buffer_before_minutes", models.PositiveSmallIntegerField(default=0)),
                ("buffer_after_minutes", models.PositiveSmallIntegerField(default=0)),
                ("meeting_location", models.CharField(choices=[("google_meet", "Google Meet"), ("phone", "Phone call"), ("in_person", "In person"), ("custom", "Custom meeting link"), ("none", "No meeting location")], default="google_meet", max_length=20)),
                ("custom_meeting_link", models.URLField(blank=True)),
                ("invite_lead_to_event", models.BooleanField(default=True)),
                ("confirmation_heading", models.CharField(default="Your call has been successfully scheduled!", max_length=80)),
                ("confirmation_message", models.CharField(default="Your slot is confirmed. We've saved your details and our team will connect with you at the scheduled time.", max_length=250)),
                ("show_booking_details", models.BooleanField(default=True)),
                ("show_add_calendar", models.BooleanField(default=True)),
                ("redirect_enabled", models.BooleanField(default=False)),
                ("redirect_button_text", models.CharField(blank=True, max_length=80)),
                ("redirect_url", models.URLField(blank=True)),
                ("current_version", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_calendar_pages", to=settings.AUTH_USER_MODEL)),
                ("host", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="hosted_calendar_pages", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_pages", to="organizations.organization")),
                ("pipeline", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="calendar_pages", to="crm.pipeline")),
                ("stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="calendar_pages", to="crm.stage")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_calendar_pages", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="CalendarBlock",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blocks", to="shvya_calendar.calendarpage")),
            ],
            options={"ordering": ["starts_at"]},
        ),
        migrations.CreateModel(
            name="CalendarPageVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="published_versions", to="shvya_calendar.calendarpage")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="calendar_page_publications", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-version"]},
        ),
        migrations.CreateModel(
            name="CalendarReminderSequence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(default="Calendar Reminders", max_length=255)),
                ("description", models.CharField(blank=True, default="Reminder messages for calendar bookings", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("page", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="reminder_sequence", to="shvya_calendar.calendarpage")),
            ],
        ),
        migrations.CreateModel(
            name="GoogleCalendarConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("calendar_id", models.CharField(default="primary", max_length=255)),
                ("access_token_ciphertext", models.TextField(blank=True)),
                ("refresh_token_ciphertext", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("scope", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="google_calendar_connections", to="organizations.organization")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="google_calendar_connection", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CalendarSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("lead_created", "Lead created"), ("lead_matched", "Existing lead matched"), ("duplicate_blocked", "Duplicate blocked"), ("invalid", "Invalid")], max_length=24)),
                ("submitted_data", models.JSONField(default=dict)),
                ("normalized_data", models.JSONField(default=dict)),
                ("attribution", models.JSONField(blank=True, default=dict)),
                ("consent_accepted", models.BooleanField(default=False)),
                ("consent_text", models.TextField(blank=True)),
                ("consent_version", models.PositiveIntegerField(default=0)),
                ("referrer", models.URLField(blank=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="calendar_submissions", to="crm.lead")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_submissions", to="organizations.organization")),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="shvya_calendar.calendarpage")),
                ("page_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="submissions", to="shvya_calendar.calendarpageversion")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CalendarReminderStep",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(choices=[("whatsapp", "WhatsApp"), ("email", "Email"), ("call_reminder", "Call Reminder")], max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, max_length=180)),
                ("body", models.TextField(blank=True)),
                ("timing_mode", models.CharField(choices=[("immediate", "Immediately after booking"), ("before", "Before booked slot"), ("specific_time", "Specific time on booking date")], default="before", max_length=20)),
                ("offset_minutes", models.IntegerField(default=-120, help_text="Minutes relative to booking start for before-slot reminders.")),
                ("specific_time", models.TimeField(blank=True, null=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="shvya_calendar.calendarremindersequence")),
            ],
            options={"ordering": ["display_order", "created_at"]},
        ),
        migrations.CreateModel(
            name="CalendarSubmissionAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("field_key", models.CharField(max_length=80)),
                ("file", models.FileField(upload_to="calendar/submissions/%Y/%m/")),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="shvya_calendar.calendarsubmission")),
            ],
        ),
        migrations.CreateModel(
            name="CalendarBooking",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("start_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField()),
                ("timezone", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("scheduled", "Scheduled"), ("rescheduled", "Rescheduled"), ("cancelled", "Cancelled"), ("completed", "Completed"), ("no_show", "No-show")], db_index=True, default="scheduled", max_length=20)),
                ("meeting_link", models.URLField(blank=True)),
                ("google_calendar_id", models.CharField(blank=True, max_length=255)),
                ("google_event_id", models.CharField(blank=True, max_length=255)),
                ("google_conference_id", models.CharField(blank=True, max_length=255)),
                ("google_event_url", models.URLField(blank=True)),
                ("calendar_sync_status", models.CharField(choices=[("not_connected", "Not connected"), ("pending", "Pending"), ("synced", "Synced"), ("failed", "Failed")], default="not_connected", max_length=20)),
                ("calendar_sync_error", models.TextField(blank=True)),
                ("cancel_token", models.CharField(editable=False, max_length=64, unique=True)),
                ("reschedule_token", models.CharField(editable=False, max_length=64, unique=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("previous_start_at", models.DateTimeField(blank=True, null=True)),
                ("previous_end_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("host", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="calendar_bookings", to=settings.AUTH_USER_MODEL)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_bookings", to="crm.lead")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_bookings", to="organizations.organization")),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bookings", to="shvya_calendar.calendarpage")),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bookings", to="shvya_calendar.calendarsubmission")),
            ],
            options={"ordering": ["-start_at"]},
        ),
        migrations.CreateModel(
            name="CalendarReminderDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("due_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("attention", "Needs call"), ("sent", "Sent"), ("completed", "Completed"), ("skipped", "Skipped"), ("failed", "Failed")], db_index=True, default="pending", max_length=20)),
                ("rendered_subject", models.CharField(blank=True, max_length=180)),
                ("rendered_body", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminder_deliveries", to="shvya_calendar.calendarbooking")),
                ("step", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deliveries", to="shvya_calendar.calendarreminderstep")),
            ],
            options={"ordering": ["due_at"]},
        ),
        migrations.AddConstraint(
            model_name="calendarpage",
            constraint=models.UniqueConstraint(fields=("organization", "slug"), name="uniq_calendar_page_org_slug"),
        ),
        migrations.AddIndex(
            model_name="calendarpage",
            index=models.Index(fields=["organization", "status"], name="cal_page_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarblock",
            index=models.Index(fields=["page", "starts_at", "ends_at"], name="cal_block_page_range_idx"),
        ),
        migrations.AddConstraint(
            model_name="calendarpageversion",
            constraint=models.UniqueConstraint(fields=("page", "version"), name="uniq_calendar_page_version"),
        ),
        migrations.AddIndex(
            model_name="calendarsubmission",
            index=models.Index(fields=["organization", "page", "created_at"], name="cal_sub_org_page_at_idx"),
        ),
        migrations.AddConstraint(
            model_name="calendarreminderstep",
            constraint=models.UniqueConstraint(fields=("sequence", "display_order"), name="uniq_calendar_reminder_step_order"),
        ),
        migrations.AddIndex(
            model_name="calendarbooking",
            index=models.Index(fields=["page", "start_at", "status"], name="cal_book_page_slot_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarbooking",
            index=models.Index(fields=["organization", "start_at"], name="cal_book_org_start_idx"),
        ),
        migrations.AddConstraint(
            model_name="calendarreminderdelivery",
            constraint=models.UniqueConstraint(fields=("booking", "step"), name="uniq_calendar_booking_reminder_step"),
        ),
        migrations.AddIndex(
            model_name="calendarreminderdelivery",
            index=models.Index(fields=["status", "due_at"], name="cal_rem_status_due_idx"),
        ),
    ]
