# Generated by Django 6.1 on 2026-09-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_attributedefinition_is_active'),
        ('shvya_calendar', '0002_calendarpage_logo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarpage',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='calendar_pages', to='crm.pipeline'),
        ),
        migrations.AlterField(
            model_name='calendarpage',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='calendar_pages', to='crm.stage'),
        ),
        migrations.AlterField(
            model_name='calendarreminderdelivery',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='shvya_calendar.calendarreminderstep'),
        ),
        migrations.AlterField(
            model_name='calendarsubmission',
            name='page_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submissions', to='shvya_calendar.calendarpageversion'),
        ),
    ]
