PRIORITY_AI_ENGAGE = 100
PRIORITY_FOLLOWUP_BUMPUP = 95
PRIORITY_AI_SUMMARY = 90
PRIORITY_SEQUENCE_STEP = 70
PRIORITY_EMAIL_SEQUENCE = 60
PRIORITY_WEBHOOK_REMINDER = 50

USER_ROLES = ("admin", "supervisor", "agent")