from django.urls import path

from apps.integrations.views.operations_mcp import (
    operations_mcp,
    operations_oauth_authorize,
    operations_oauth_register,
    operations_oauth_revoke,
    operations_oauth_resource_metadata,
    operations_oauth_server_metadata,
    operations_oauth_token,
)

from apps.integrations.views.mcp import (
    diagnostic_mcp,
    diagnostic_oauth_authorize,
    diagnostic_oauth_register,
    diagnostic_oauth_revoke,
    diagnostic_oauth_resource_metadata,
    diagnostic_oauth_server_metadata,
    diagnostic_oauth_token,
)


urlpatterns = [
    # RFC 8414 metadata location for issuer https://<host>/operations.
    path(
        ".well-known/oauth-authorization-server/operations",
        operations_oauth_server_metadata,
        name="shvya-operations-oauth-server-metadata-rfc8414",
    ),
    path(
        "operations/.well-known/oauth-protected-resource",
        operations_oauth_resource_metadata,
        name="shvya-operations-oauth-resource-metadata",
    ),
    path(
        "operations/.well-known/oauth-authorization-server",
        operations_oauth_server_metadata,
        name="shvya-operations-oauth-server-metadata",
    ),
    path(
        "operations/oauth/register",
        operations_oauth_register,
        name="shvya-operations-oauth-register",
    ),
    path(
        "operations/oauth/authorize",
        operations_oauth_authorize,
        name="shvya-operations-oauth-authorize",
    ),
    path(
        "operations/oauth/token",
        operations_oauth_token,
        name="shvya-operations-oauth-token",
    ),
    path(
        "operations/oauth/revoke",
        operations_oauth_revoke,
        name="shvya-operations-oauth-revoke",
    ),
    path(
        "operations/mcp/",
        operations_mcp,
        name="shvya-operations-mcp",
    ),
    path(
        ".well-known/oauth-protected-resource",
        diagnostic_oauth_resource_metadata,
        name="shvya-diagnostic-oauth-resource-metadata",
    ),
    path(
        ".well-known/oauth-authorization-server",
        diagnostic_oauth_server_metadata,
        name="shvya-diagnostic-oauth-server-metadata",
    ),
    path(
        "oauth/register",
        diagnostic_oauth_register,
        name="shvya-diagnostic-oauth-register",
    ),
    path(
        "oauth/authorize",
        diagnostic_oauth_authorize,
        name="shvya-diagnostic-oauth-authorize",
    ),
    path(
        "oauth/token",
        diagnostic_oauth_token,
        name="shvya-diagnostic-oauth-token",
    ),
    path(
        "oauth/revoke",
        diagnostic_oauth_revoke,
        name="shvya-diagnostic-oauth-revoke",
    ),
    path(
        "mcp/",
        diagnostic_mcp,
        name="shvya-diagnostic-mcp",
    ),
]
