import django.db.models.deletion
import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0005_apikey_can_read_diagnostics"),
        ("crm", "0030_alter_lead_lead_source_call"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallAppRelease",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version_name", models.CharField(max_length=40)),
                ("version_code", models.PositiveIntegerField(unique=True)),
                ("download_url", models.URLField(max_length=1000)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("min_android_sdk", models.PositiveIntegerField(default=23)),
                ("release_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-version_code", "-created_at"]},
        ),
        migrations.CreateModel(
            name="CallIntelligenceSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=True)),
                ("auto_create_answered_incoming", models.BooleanField(default=True)),
                ("auto_create_answered_outgoing", models.BooleanField(default=True)),
                ("auto_create_missed", models.BooleanField(default=True)),
                ("auto_create_rejected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("default_pipeline", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="crm.pipeline")),
                ("default_stage", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="crm.stage")),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="call_intelligence_settings", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="CallDevice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_id", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("android_version", models.CharField(blank=True, max_length=50)),
                ("app_version", models.CharField(blank=True, max_length=50)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("battery_optimization_ignored", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="call_intelligence_devices", to="organizations.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="call_intelligence_devices", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CallRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source", models.CharField(choices=[("android_sim", "Android SIM"), ("cloud", "Cloud telephony"), ("manual", "Manual")], default="android_sim", max_length=24)),
                ("source_call_id", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=32)),
                ("raw_phone_number", models.CharField(blank=True, max_length=64)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("direction", models.CharField(choices=[("incoming", "Incoming"), ("outgoing", "Outgoing")], max_length=16)),
                ("status", models.CharField(choices=[("answered", "Answered"), ("missed", "Missed"), ("rejected", "Rejected"), ("busy", "Busy"), ("no_answer", "No Answer"), ("failed", "Failed"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("sub_status", models.CharField(blank=True, max_length=40)),
                ("call_name", models.CharField(default="Phone Call", max_length=150)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ringing_at", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("ring_duration_seconds", models.PositiveIntegerField(default=0)),
                ("talk_duration_seconds", models.PositiveIntegerField(default=0)),
                ("total_duration_seconds", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("disposition", models.CharField(blank=True, max_length=80)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("sync_status", models.CharField(choices=[("pending", "Pending"), ("syncing", "Syncing"), ("synced", "Synced"), ("failed", "Failed")], default="synced", max_length=16)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("last_sync_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("crm_call", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="intelligence_record", to="crm.leadcall")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="calls", to="telephony.calldevice")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="intelligent_calls", to="crm.lead")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="call_intelligence_calls", to="organizations.organization")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="call_intelligence_calls", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-ended_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="CallEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_uuid", models.UUIDField(unique=True)),
                ("event_type", models.CharField(choices=[("started", "Started"), ("ringing", "Ringing"), ("answered", "Answered"), ("completed", "Completed"), ("missed", "Missed"), ("rejected", "Rejected"), ("busy", "Busy"), ("no_answer", "No Answer"), ("failed", "Failed"), ("reconciled", "Reconciled")], max_length=20)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("call", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="telephony.callrecord")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="telephony.calldevice")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="call_intelligence_events", to="organizations.organization")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="call_intelligence_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["occurred_at", "created_at"]},
        ),
        migrations.CreateModel(
            name="CallIntelligenceResult",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("summary", models.TextField(blank=True)),
                ("intent", models.CharField(choices=[("unknown", "Unknown"), ("low", "Low"), ("medium", "Medium"), ("high", "High")], default="unknown", max_length=16)),
                ("sentiment", models.CharField(choices=[("unknown", "Unknown"), ("negative", "Negative"), ("neutral", "Neutral"), ("positive", "Positive")], default="unknown", max_length=16)),
                ("outcome", models.CharField(blank=True, max_length=255)),
                ("objections", models.JSONField(blank=True, default=list)),
                ("buying_signals", models.JSONField(blank=True, default=list)),
                ("competitor", models.CharField(blank=True, max_length=255)),
                ("budget", models.CharField(blank=True, max_length=255)),
                ("timeline", models.CharField(blank=True, max_length=255)),
                ("next_action", models.CharField(blank=True, max_length=255)),
                ("extracted_attributes", models.JSONField(blank=True, default=list)),
                ("raw_analysis", models.JSONField(blank=True, default=dict)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("call", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="intelligence", to="telephony.callrecord")),
            ],
        ),
        migrations.AddConstraint(
            model_name="callrecord",
            constraint=models.UniqueConstraint(fields=("organization", "device", "source", "source_call_id"), name="telephony_source_call_unique"),
        ),
        migrations.AddIndex(
            model_name="calldevice",
            index=models.Index(fields=["organization", "user", "is_active"], name="telephony_device_user_idx"),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(fields=["organization", "-ended_at"], name="telephony_org_call_at_idx"),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(fields=["lead", "-ended_at"], name="telephony_lead_call_idx"),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(fields=["user", "-ended_at"], name="telephony_user_call_idx"),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(fields=["organization", "status"], name="telephony_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="callevent",
            index=models.Index(fields=["call", "occurred_at"], name="telephony_call_event_idx"),
        ),
    ]
