# Generated by Django 6.1.1 on 2026-10-05 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_instagram_phone_optional'),
        ('organizations', '0007_organizationdeletioncleanup'),
        ('telephony', '0002_standard_callback_disposition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='analysis_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='analysis_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='analysis_input_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='analysis_status',
            field=models.CharField(choices=[('not_requested', 'Add notes'), ('queued', 'AI queued'), ('processing', 'Analyzing'), ('completed', 'Analyzed'), ('failed', 'Analysis failed')], default='not_requested', max_length=16),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='analysis_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['organization', 'phone_number'], name='telephony_org_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['analysis_status', 'analysis_updated_at'], name='telephony_analysis_due_idx'),
        ),
    ]
