# Generated by Django 6.1 for SHVYA Auto Follow-ups.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
        ("crm", "0012_lead_lead_source"),
        ("channels", "0010_whatsapptemplatemetadata_carousel_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoFollowupSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("enabled", models.BooleanField(default=False)),
                ("business_hours_start", models.TimeField(default="07:30")),
                ("business_hours_end", models.TimeField(default="19:30")),
                ("conversation_delay_value", models.PositiveIntegerField(default=2)),
                ("conversation_delay_unit", models.CharField(choices=[("minutes", "Minutes"), ("hours", "Hours"), ("days", "Days")], default="hours", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="auto_followup_settings", to="organizations.organization")),
            ],
        ),
        migrations.CreateModel(
            name="FollowupSequence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_followup_sequences", to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="followup_sequences", to="organizations.organization")),
                ("whatsapp_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="followup_sequences", to="channels.whatsappaccount")),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["organization", "is_active", "updated_at"], name="fu_seq_org_active_idx")],
                "constraints": [models.UniqueConstraint(fields=("organization", "name"), name="fu_seq_org_name_uniq")],
            },
        ),
        migrations.CreateModel(
            name="FollowupStep",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField(default=1)),
                ("step_type", models.CharField(choices=[("whatsapp", "WhatsApp API"), ("email", "Email"), ("reminder", "Call Reminder")], max_length=12)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                ("reminder_text", models.TextField(blank=True)),
                ("schedule_type", models.CharField(choices=[("immediate", "Immediately"), ("delay", "After X minutes/hours/days"), ("specific_time", "Specific time"), ("recurring", "Recurring")], default="immediate", max_length=16)),
                ("delay_value", models.PositiveIntegerField(blank=True, null=True)),
                ("delay_unit", models.CharField(blank=True, choices=[("minutes", "Minutes"), ("hours", "Hours"), ("days", "Days")], max_length=10)),
                ("specific_time", models.TimeField(blank=True, null=True)),
                ("specific_weekday", models.SmallIntegerField(blank=True, choices=[(0, "Sunday"), (1, "Monday"), (2, "Tuesday"), (3, "Wednesday"), (4, "Thursday"), (5, "Friday"), (6, "Saturday")], null=True)),
                ("recurring_every", models.PositiveIntegerField(blank=True, null=True)),
                ("recurring_unit", models.CharField(blank=True, choices=[("minutes", "Minutes"), ("hours", "Hours"), ("days", "Days")], max_length=10)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("retry_delay_hours", models.PositiveSmallIntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="followups.followupsequence")),
                ("whatsapp_template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="followup_steps", to="channels.whatsapptemplate")),
            ],
            options={
                "ordering": ["position", "created_at"],
                "indexes": [models.Index(fields=["sequence", "position", "is_active"], name="fu_step_seq_order_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("sequence", "position"), name="fu_step_seq_position_uniq"),
                    models.CheckConstraint(condition=models.Q(("retry_count__gte", 0), ("retry_count__lte", 5)), name="fu_step_retry_lte_5"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeadSequenceState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("active", "Active"), ("paused", "Paused"), ("inactive", "Inactive"), ("completed", "Completed"), ("cleared", "Cleared")], default="active", max_length=12)),
                ("lead_auto_followup_enabled", models.BooleanField(default=True)),
                ("last_completed_position", models.PositiveIntegerField(default=0)),
                ("upcoming_send_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_step_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("last_manual_outbound_at", models.DateTimeField(blank=True, null=True)),
                ("paused_until", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="followup_sequence_states", to="crm.lead")),
                ("next_step", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="next_for_states", to="followups.followupstep")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lead_sequence_states", to="organizations.organization")),
                ("sequence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lead_states", to="followups.followupsequence")),
            ],
            options={
                "ordering": ["upcoming_send_at", "assigned_at"],
                "indexes": [
                    models.Index(fields=["organization", "status", "upcoming_send_at"], name="fu_state_org_due_idx"),
                    models.Index(fields=["sequence", "status"], name="fu_state_seq_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("lead", "sequence"), name="fu_state_lead_seq_uniq"),
                    models.UniqueConstraint(condition=models.Q(("status__in", ["active", "paused"])), fields=("lead",), name="fu_state_one_active_lead"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FollowupExecution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("sent", "Sent"), ("created", "Reminder created"), ("retry_wait", "Retry wait"), ("skipped", "Skipped"), ("blocked", "Blocked"), ("failed", "Failed")], default="pending", max_length=12)),
                ("attempt_no", models.PositiveSmallIntegerField(default=1)),
                ("max_attempts", models.PositiveSmallIntegerField(default=1)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("email_message_id", models.CharField(blank=True, max_length=255)),
                ("error", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="followup_executions", to="crm.lead")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="followup_executions", to="organizations.organization")),
                ("reminder", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="followup_executions", to="crm.leadreminder")),
                ("sequence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="followups.followupsequence")),
                ("state", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="executions", to="followups.leadsequencestate")),
                ("step", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="executions", to="followups.followupstep")),
                ("whatsapp_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="followup_executions", to="channels.whatsappmessage")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["state", "step", "status"], name="fu_exec_state_step_idx"),
                    models.Index(fields=["organization", "status", "scheduled_for"], name="fu_exec_org_due_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FollowupSenderState",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("next_available_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="followup_sender_state", to="channels.whatsappaccount")),
                ("last_lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="last_followup_sender_states", to="crm.lead")),
            ],
        ),
    ]
