# Generated by Django 6.1 on 2026-09-20 18:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0004_pipeline_scoped_automation_settings'),
        ('organizations', '0005_apikey_can_read_diagnostics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchpointCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TouchpointReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='followups.touchpointcategory')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='touchpointcategory',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='touchpoint_org_category_uniq'),
        ),
    ]
