# Generated by Django 6.1 on 2026-09-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0015_instagramconversation_lead'),
        ('followups', '0006_touchpointreply_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupexecution',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='executions', to='followups.followupstep'),
        ),
        migrations.AlterField(
            model_name='followupsequence',
            name='whatsapp_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='followup_sequences', to='channels.whatsappaccount'),
        ),
        migrations.AlterField(
            model_name='followupstep',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='followup_steps', to='channels.whatsapptemplate'),
        ),
    ]
