# Generated by Django 6.1 on 2026-09-24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followups", "0007_alter_followupexecution_step_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowupStepAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="followups/email/%Y/%m/%d/"),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("position", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="followups.followupstep",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="followupstepattachment",
            constraint=models.UniqueConstraint(
                fields=("step", "position"),
                name="fu_step_attachment_position_uniq",
            ),
        ),
    ]
