# Generated by Django 6.1.1 on 2026-10-04 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0020_whatsapptemplatectaevent'),
        ('followups', '0008_followupstepattachment'),
        ('organizations', '0007_organizationdeletioncleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followupsequence',
            name='instagram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='followup_sequences', to='channels.instagramaccount'),
        ),
        migrations.AddField(
            model_name='followupstep',
            name='instagram_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='followupsequence',
            name='whatsapp_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='followup_sequences', to='channels.whatsappaccount'),
        ),
        migrations.AlterField(
            model_name='followupstep',
            name='step_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp API'), ('instagram', 'Instagram DM'), ('email', 'Email'), ('reminder', 'Call Reminder')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='followupsequence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instagram_account__isnull', True), ('whatsapp_account__isnull', False)), models.Q(('instagram_account__isnull', False), ('whatsapp_account__isnull', True)), _connector='OR'), name='fu_seq_exactly_one_channel'),
        ),
    ]
