# Generated by Django 6.1 on 2026-08-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('organizations', '0002_alter_apikey_options_apikey_can_upsert_leads_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_owner_i_ecc77c_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_last_ac_cf6e47_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='crm_lead_next_fo_8a3bfb_idx',
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='ai_on',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='visible',
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_org_pipeline_name'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'name'), name='uniq_pipeline_stage_name'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ai_enabled',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='ai_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_activity_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='next_followup_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
    ]
