# Generated by Django 6.1 on 2026-08-15 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_stage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelinePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view_pipeline', models.BooleanField(default=True)),
                ('can_create_leads', models.BooleanField(default=False)),
                ('can_edit_leads', models.BooleanField(default=False)),
                ('can_move_leads', models.BooleanField(default=False)),
                ('can_delete_leads', models.BooleanField(default=False)),
                ('can_manage_stages', models.BooleanField(default=False)),
                ('can_manage_pipeline', models.BooleanField(default=False)),
                ('can_manage_lead_fields', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_api_keys', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='crm.pipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pipeline', 'user'), name='uniq_pipeline_user_permission')],
            },
        ),
    ]
