# Generated by Django 6.1 on 2026-08-16 11:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_leadcall_leadnote_leadreminder'),
        ('organizations', '0002_alter_apikey_options_apikey_can_upsert_leads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='crm.lead')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.tag')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_org_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='leadtag',
            constraint=models.UniqueConstraint(fields=('lead', 'tag'), name='uniq_lead_tag'),
        ),
    ]
