# Generated by Django 6.1 on 2026-08-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_tag_leadtag_tag_uniq_org_tag_name_and_more'),
        ('organizations', '0003_organizationtag_organization_assigned_poc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_tags', to='organizations.organization'),
        ),
    ]
