# Generated by Django 6.1 on 2026-08-27 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_pipeline_country_code_pipeline_owner_and_more'),
        ('organizations', '0004_organizationpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('pipeline_changed', 'Pipeline Changed'), ('stage_changed', 'Stage Changed'), ('note_added', 'Note Added'), ('call_logged', 'Call Logged'), ('reminder_created', 'Reminder Created'), ('reminder_completed', 'Reminder Completed')], max_length=50)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('old_pipeline_name', models.CharField(blank=True, max_length=255)),
                ('new_pipeline_name', models.CharField(blank=True, max_length=255)),
                ('old_stage_name', models.CharField(blank=True, max_length=255)),
                ('new_stage_name', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('new_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pipeline')),
                ('new_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.stage')),
                ('old_pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pipeline')),
                ('old_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.stage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_activities', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'lead', '-created_at'], name='crm_leadact_organiz_4de33f_idx'), models.Index(fields=['lead', '-created_at'], name='crm_leadact_lead_id_639066_idx'), models.Index(fields=['topic', '-created_at'], name='crm_leadact_topic_0de074_idx')],
            },
        ),
    ]
