# Generated by Django 6.1 on 2026-08-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_leadcall_call_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('system', 'System'), ('external_api', 'External API'), ('whatsapp_api', 'WhatsApp API'), ('google_sheets', 'Google Sheets'), ('csv_import', 'CSV Import')], default='system', max_length=30),
        ),
    ]
