# Generated by Django 6.1 on 2026-08-28 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_lead_source'),
        ('organizations', '0004_organizationpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('numeric', 'Numeric'), ('date', 'Date'), ('datetime', 'Datetime'), ('option', 'Option Picker')], default='text', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_attribute_definitions', to='organizations.organization')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['organization', 'display_order'], name='crm_attribu_organiz_6f3260_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='uniq_org_attribute_name'), models.UniqueConstraint(fields=('organization', 'key'), name='uniq_org_attribute_key')],
            },
        ),
    ]
