# Generated by Django 6.1 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_attributedefinition'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stage',
            name='uniq_pipeline_stage_name',
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('pipeline', 'name'), name='uniq_active_pipeline_stage_name'),
        ),
    ]
