# Generated by Django 6.1 on 2026-08-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_stage_uniq_pipeline_stage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, help_text='Describe what this stage means and what should happen while a lead is in this stage.'),
        ),
    ]
