# Generated by Django 6.1 on 2026-09-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_stage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='ai_on',
            field=models.BooleanField(default=True, help_text='Allow SHVYA AI to engage leads while they are in this stage.'),
        ),
    ]
