# Generated by Django 6.1 on 2026-09-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_stage_ai_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Allow SHVYA AI to engage this lead.'),
        ),
    ]
