# Generated by Django 6.1.1 on 2026-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_leadremindernotificationack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('system', 'System'), ('external_api', 'External API'), ('whatsapp_api', 'WhatsApp API'), ('whatsapp', 'WhatsApp'), ('google_sheets', 'Google Sheet'), ('csv_import', 'CSV Import'), ('meta_ads', 'Meta Ads'), ('instagram', 'Instagram')], default='system', max_length=30),
        ),
    ]
