# Generated by Django 6.1.1 on 2026-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_alter_lead_lead_source_justdial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('system', 'System'), ('external_api', 'External API'), ('whatsapp_api', 'WhatsApp API'), ('whatsapp', 'WhatsApp'), ('google_sheets', 'Google Sheet'), ('indiamart', 'IndiaMART'), ('csv_import', 'CSV Import'), ('meta_ads', 'Meta Ads'), ('instagram', 'Instagram'), ('shvya_calendar', 'SHVYA Calendar'), ('phone_call', 'Phone Call'), ('justdial', 'JustDial')], default='system', max_length=30),
        ),
    ]
