# Generated by Django 6.1 on 2026-09-23 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_package'),
        ('support', '0002_seed_shvya_ops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='merged_sources', to='support.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requested_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='origin_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='original_messages', to='support.ticket'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='support_work_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
