# Generated by Django 6.1 on 2026-09-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_link_generated', 'Login link generated'), ('password_reset', 'Password reset'), ('user_activated', 'User activated'), ('user_deactivated', 'User deactivated'), ('user_created', 'User created'), ('organization_deleted', 'Organization deleted'), ('organization_tag_updated', 'Organization tag updated'), ('organization_tag_deleted', 'Organization tag deleted'), ('organization_created', 'Organization created'), ('organization_updated', 'Organization updated')], max_length=32),
        ),
    ]
