# Generated by Django 6.1 on 2026-09-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('platform_email_updated', 'Platform email updated'), ('login_link_generated', 'Login link generated'), ('password_reset', 'Password reset'), ('user_activated', 'User activated'), ('user_deactivated', 'User deactivated'), ('user_created', 'User created'), ('organization_deleted', 'Organization deleted'), ('organization_tag_updated', 'Organization tag updated'), ('organization_tag_deleted', 'Organization tag deleted'), ('organization_created', 'Organization created'), ('organization_updated', 'Organization updated')], max_length=32),
        ),
        migrations.CreateModel(
            name='PlatformEmailConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(default='SHVYA AI', max_length=120)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='starttls', max_length=16)),
                ('smtp_username', models.CharField(max_length=254)),
                ('encrypted_password', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='singleton_platform_email')],
            },
        ),
    ]
