# Generated by Django 6.1.1 on 2026-10-07 18:11

import apps.vault.models
import apps.vault.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_organizationdeletioncleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(default=apps.vault.models.vault_slug, max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=16)),
                ('is_paused', models.BooleanField(default=False)),
                ('access_code_hash', models.CharField(max_length=256)),
                ('access_version', models.PositiveIntegerField(default=1)),
                ('failed_access_attempts', models.PositiveSmallIntegerField(default=0)),
                ('access_locked_until', models.DateTimeField(blank=True, null=True)),
                ('token_hash', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('token_prefix', models.CharField(blank=True, editable=False, max_length=16)),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('storage_quota_bytes', models.PositiveBigIntegerField(default=2147483648)),
                ('storage_used_bytes', models.PositiveBigIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('website', 'Website pages'), ('brochures', 'Brochures, catalogues & price lists'), ('media', 'Photos & videos the AI can send'), ('offerings', 'Products, services & pricing'), ('basics', 'Business basics'), ('faqs', 'Questions customers ask & objections'), ('team', 'Who handles leads'), ('qualification', 'Qualification'), ('handoff', 'When the AI should hand over to a human'), ('blacklist', 'Topics the AI must never answer'), ('rules', 'Tone, language & promises'), ('proof', 'Testimonials & proof'), ('offers', 'Current offers'), ('scripts', 'Sales scripts & past chats'), ('other', 'Anything else')], max_length=24)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('link', 'Link'), ('file', 'File'), ('audio', 'Voice note')], default='note', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('file', models.FileField(blank=True, max_length=300, storage=apps.vault.storage.VaultPrivateStorage(), upload_to=apps.vault.storage.vault_upload_path)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('author_type', models.CharField(choices=[('client', 'Client'), ('team', 'SHVYA team'), ('agent', 'Agent')], default='client', max_length=16)),
                ('origin', models.CharField(choices=[('fireflies', 'Call transcript'), ('whatsapp', 'WhatsApp'), ('ops_chat', 'SHVYA team'), ('other', 'Other')], default='other', max_length=16)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_body', models.TextField(blank=True, null=True)),
                ('client_edited_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_for_ai_sharing', models.BooleanField(default=False)),
                ('send_when', models.TextField(blank=True)),
                ('transcription_status', models.CharField(choices=[('not_requested', 'Not requested'), ('unavailable', 'Unavailable'), ('provided', 'Provided')], default='not_requested', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vault_entries', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vault.vault')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VaultEntryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('client_body', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor_type', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='vault.vaultentry')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='VaultEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('updated', 'Client updated'), ('submitted', 'Submitted'), ('access_rotated', 'Access code changed'), ('token_rotated', 'Agent token changed')], max_length=24)),
                ('section', models.CharField(blank=True, choices=[('website', 'Website pages'), ('brochures', 'Brochures, catalogues & price lists'), ('media', 'Photos & videos the AI can send'), ('offerings', 'Products, services & pricing'), ('basics', 'Business basics'), ('faqs', 'Questions customers ask & objections'), ('team', 'Who handles leads'), ('qualification', 'Qualification'), ('handoff', 'When the AI should hand over to a human'), ('blacklist', 'Topics the AI must never answer'), ('rules', 'Tone, language & promises'), ('proof', 'Testimonials & proof'), ('offers', 'Current offers'), ('scripts', 'Sales scripts & past chats'), ('other', 'Anything else')], max_length=24)),
                ('actor_type', models.CharField(default='team', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vault.vault')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultProfileSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft for review'), ('reviewed', 'Reviewed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_snapshots', to='vault.vault')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('website', 'Website pages'), ('brochures', 'Brochures, catalogues & price lists'), ('media', 'Photos & videos the AI can send'), ('offerings', 'Products, services & pricing'), ('basics', 'Business basics'), ('faqs', 'Questions customers ask & objections'), ('team', 'Who handles leads'), ('qualification', 'Qualification'), ('handoff', 'When the AI should hand over to a human'), ('blacklist', 'Topics the AI must never answer'), ('rules', 'Tone, language & promises'), ('proof', 'Testimonials & proof'), ('offers', 'Current offers'), ('scripts', 'Sales scripts & past chats'), ('other', 'Anything else')], default='other', max_length=24)),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('author_type', models.CharField(choices=[('client', 'Client'), ('team', 'SHVYA team'), ('agent', 'Agent')], default='team', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vault.vault')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VaultSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('website', 'Website pages'), ('brochures', 'Brochures, catalogues & price lists'), ('media', 'Photos & videos the AI can send'), ('offerings', 'Products, services & pricing'), ('basics', 'Business basics'), ('faqs', 'Questions customers ask & objections'), ('team', 'Who handles leads'), ('qualification', 'Qualification'), ('handoff', 'When the AI should hand over to a human'), ('blacklist', 'Topics the AI must never answer'), ('rules', 'Tone, language & promises'), ('proof', 'Testimonials & proof'), ('offers', 'Current offers'), ('scripts', 'Sales scripts & past chats'), ('other', 'Anything else')], max_length=24)),
                ('state', models.CharField(choices=[('empty', 'Empty'), ('filled', 'Filled'), ('dont_have', "We don't have this")], default='empty', max_length=16)),
                ('is_done', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='vault.vault')),
            ],
        ),
        migrations.CreateModel(
            name='VaultCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('attendees', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('share_recording', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='vault.vault')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('vault', 'external_id'), name='vault_call_external_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='vaultentry',
            index=models.Index(fields=['vault', 'section'], name='vault_entry_section_idx'),
        ),
        migrations.AddConstraint(
            model_name='vaultentry',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('vault', 'author_type', 'external_id'), name='vault_entry_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='vaultquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('vault', 'author_type', 'external_id'), name='vault_question_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='vaultsection',
            constraint=models.UniqueConstraint(fields=('vault', 'key'), name='vault_section_unique'),
        ),
    ]
