import hashlib

from django.contrib import messages
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils import timezone

from apps.organizations.models import Organization

from .models import OneTimeLoginToken
from django.conf import settings
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .models import User

from .session_utils import (
    get_session_store,
    save_session_cookie,
    set_authenticated_user,
    clear_authenticated_user,
    delete_session_cookie,
)


# ============================================================
# PUBLIC CRM SIGNUP
# ============================================================


def crm_signup_view(request):
    """
    Public SHVYA CRM signup.

    Signup creates:

        1. A new Organization
        2. The first User belonging to that Organization

    Organization:

        name       = company_name submitted by the user
        plan       = "free"
        is_active  = True
        created_at = automatically generated by Django

    User:

        name         = submitted name
        email        = submitted email
        phone        = submitted phone number
        organization = newly created organization
        role         = Admin
        is_active    = True
        password     = securely hashed
        created_at   = automatically generated by Django

    The user is NOT automatically logged into the CRM.

    After successful signup, the user is redirected to the
    CRM login page.
    """

    # --------------------------------------------------------
    # Already authenticated CRM users do not need signup.
    # --------------------------------------------------------

    if request.method == "GET":

        return render(
            request,
            "crm/signup.html",
        )

    # --------------------------------------------------------
    # Read submitted fields.
    # --------------------------------------------------------

    name = request.POST.get(
        "name",
        "",
    ).strip()

    email = request.POST.get(
        "email",
        "",
    ).strip()

    phone = request.POST.get(
        "phone",
        "",
    ).strip()

    company_name = request.POST.get(
        "company_name",
        "",
    ).strip()

    password = request.POST.get(
        "password",
        "",
    )

    # --------------------------------------------------------
    # Basic required-field validation.
    # --------------------------------------------------------

    errors = {}

    if not name:
        errors["name"] = "Name is required."

    if not email:
        errors["email"] = "Email is required."

    if not phone:
        errors["phone"] = "Phone number is required."

    if not company_name:
        errors["company_name"] = (
            "Company name is required."
        )

    if not password:
        errors["password"] = (
            "Password is required."
        )

    # --------------------------------------------------------
    # Normalize email.
    # --------------------------------------------------------

    if email:
        email = User.objects.normalize_email(
            email
        )

    # --------------------------------------------------------
    # Validate email format using Django's EmailValidator.
    # --------------------------------------------------------

    if email:

        from django.core.validators import validate_email

        try:

            validate_email(email)

        except ValidationError:

            errors["email"] = (
                "Enter a valid email address."
            )

    # --------------------------------------------------------
    # Password validation.
    # --------------------------------------------------------

    if password:

        try:

            password_validation.validate_password(
                password
            )

        except ValidationError as exc:

            errors["password"] = (
                " ".join(exc.messages)
            )

    # --------------------------------------------------------
    # Prevent signup with an already-used email.
    #
    # Although the database constraint is organization +
    # email, public signup should not create ambiguity by
    # allowing the same email to create multiple accounts.
    # --------------------------------------------------------

    if email:

        if User.objects.filter(
            email__iexact=email
        ).exists():

            errors["email"] = (
                "An account with this email address "
                "already exists."
            )

    # --------------------------------------------------------
    # Return form with validation errors.
    # --------------------------------------------------------

    if errors:

        return render(
            request,
            "crm/signup.html",
            {
                "errors": errors,
                "form_data": {
                    "name": name,
                    "email": email,
                    "phone": phone,
                    "company_name": company_name,
                },
            },
            status=400,
        )

    # --------------------------------------------------------
    # Create Organization + User atomically.
    #
    # If either creation fails, neither record remains in
    # the database.
    # --------------------------------------------------------

    try:

        with transaction.atomic():

            organization = Organization.objects.create(
                name=company_name,
                plan="free",
                is_active=True,
            )

            user = User.objects.create_user(
                email=email,
                organization=organization,
                password=password,
                name=name,
                phone=phone,
                role=User.Role.ADMIN,
                is_active=True,
                is_staff=False,
                is_superuser=False,
            )

    except IntegrityError:

        return render(
            request,
            "crm/signup.html",
            {
                "errors": {
                    "email": (
                        "An account with this email address "
                        "already exists."
                    )
                },
                "form_data": {
                    "name": name,
                    "email": email,
                    "phone": phone,
                    "company_name": company_name,
                },
            },
            status=400,
        )

    except Exception:

        return render(
            request,
            "crm/signup.html",
            {
                "errors": {
                    "general": (
                        "Unable to create your account "
                        "right now. Please try again."
                    )
                },
                "form_data": {
                    "name": name,
                    "email": email,
                    "phone": phone,
                    "company_name": company_name,
                },
            },
            status=500,
        )

    # --------------------------------------------------------
    # Success message.
    # --------------------------------------------------------

    messages.success(
        request,
        (
            "Your SHVYA AI account has been created "
            "successfully. Please log in to continue."
        ),
    )

    # --------------------------------------------------------
    # Redirect to CRM login.
    # --------------------------------------------------------

    return redirect(
        "crm-login"
    )


# ============================================================
# ONE-TIME CRM LOGIN
# ============================================================


def one_time_login_view(request):
    """
    Authenticate a CRM user through a secure one-time login token.

    The CRM user is authenticated into the dedicated SHVYA CRM
    session instead of Django's default sessionid cookie.

    Session separation:

        /admin/       -> sessionid
        /superadmin/  -> shvya_superadmin_sessionid
        /dashboard/  -> shvya_crm_sessionid

    The one-time login token is:

        - hashed before lookup
        - validated for expiration
        - validated against the organization
        - validated against the user's active state
        - marked as used after successful validation
        - stored in the dedicated CRM session
    """

    # =========================================================
    # GET TOKEN
    # =========================================================

    raw_token = request.GET.get(
        "token",
        "",
    ).strip()

    if not raw_token:
        return HttpResponse(
            "Invalid or missing login token.",
            status=400,
        )

    # =========================================================
    # HASH TOKEN
    # =========================================================

    token_hash = hashlib.sha256(
        raw_token.encode("utf-8")
    ).hexdigest()

    # =========================================================
    # FIND TOKEN
    # =========================================================

    token = (
        OneTimeLoginToken.objects
        .select_related(
            "user",
            "organization",
        )
        .filter(
            token_hash=token_hash,
        )
        .first()
    )

    if token is None:
        return HttpResponse(
            "Invalid or expired login link.",
            status=400,
        )

    # =========================================================
    # VALIDATE TOKEN
    # =========================================================

    now = timezone.now()

    # ---------------------------------------------------------
    # Already used
    # ---------------------------------------------------------

    if token.used_at is not None:
        return HttpResponse(
            "This login link has already been used.",
            status=400,
        )

    # ---------------------------------------------------------
    # Expired
    # ---------------------------------------------------------

    if token.expires_at <= now:
        return HttpResponse(
            "This login link has expired.",
            status=400,
        )

    # =========================================================
    # VALIDATE USER
    # =========================================================

    user = token.user

    # ---------------------------------------------------------
    # User must be active
    # ---------------------------------------------------------

    if not user.is_active:
        return HttpResponse(
            "This user account is disabled.",
            status=403,
        )

    # ---------------------------------------------------------
    # User organization must match token organization
    # ---------------------------------------------------------

    if user.organization_id != token.organization_id:
        return HttpResponse(
            "Invalid login token.",
            status=400,
        )

    # ---------------------------------------------------------
    # User must belong to an organization
    # ---------------------------------------------------------

    if user.organization_id is None:
        return HttpResponse(
            "This user is not associated with an organization.",
            status=400,
        )

    # =========================================================
    # LOAD DEDICATED CRM SESSION
    # =========================================================

    crm_session = get_session_store(
        request,
        "dashboard",
    )

    # =========================================================
    # AUTHENTICATE USER INTO CRM SESSION
    # =========================================================
    #
    # The CRM uses its own session instead of Django's default
    # request.session authentication.
    #
    # This keeps:
    #
    #     Django Admin
    #     Superadmin
    #     CRM Dashboard
    #
    # independently authenticated.
    #

    set_authenticated_user(
        crm_session,
        user,
    )

    # =========================================================
    # MARK TOKEN AS USED
    # =========================================================
    #
    # Only mark the token as used after all validation has
    # succeeded and immediately before returning the successful
    # login response.
    #

    token.used_at = now

    token.save(
        update_fields=[
            "used_at",
        ],
    )

    # =========================================================
    # REDIRECT TO CRM DASHBOARD
    # =========================================================

    response = redirect(
        "/dashboard/",
    )

    # =========================================================
    # SAVE DEDICATED CRM COOKIE
    # =========================================================

    save_session_cookie(
        request,
        response,
        crm_session,
        "dashboard",
    )

    # =========================================================
    # PREVENT CACHED LOGIN RESPONSE
    # =========================================================

    response["Cache-Control"] = (
        "no-cache, no-store, must-revalidate"
    )

    response["Pragma"] = "no-cache"
    response["Expires"] = "0"

    return response


# ============================================================
# CRM LOGOUT
# ============================================================


def crm_logout_view(request):
    """
    Completely log the user out of the dedicated CRM session.

    This does NOT log the user out of:

        - Django Admin
        - SHVYA Superadmin
        - other SHVYA sessions

    It only destroys the dedicated CRM session:

        shvya_crm_sessionid

    After logout:

        /logout/
            ↓
        /dashboard/login/
            ↓
        CRM login page

    IMPORTANT:

    We deliberately flush the dedicated CRM session instead of
    only removing authentication keys.

    This guarantees that the previous CRM authentication state
    cannot remain inside the old session.
    """

    # =========================================================
    # LOAD CURRENT CRM SESSION
    # =========================================================

    crm_session = get_session_store(
        request,
        "dashboard",
    )

    # =========================================================
    # COMPLETELY DESTROY CRM SESSION
    # =========================================================
    #
    # flush():
    #
    #   1. creates a new empty session
    #   2. deletes the old session data
    #   3. removes the old authentication state
    #
    # This is stronger than simply doing:
    #
    #     session.pop("_auth_user_id")
    #
    # because the entire old CRM session is invalidated.
    #

    try:
        crm_session.flush()

    except Exception:
        # -----------------------------------------------------
        # Fallback
        # -----------------------------------------------------
        #
        # If flush() cannot complete, attempt to delete the
        # existing database-backed session.
        #

        try:
            crm_session.delete()

        except Exception:
            pass

    # =========================================================
    # REDIRECT TO CRM LOGIN PAGE
    # =========================================================
    #
    # IMPORTANT:
    #
    # Use the named CRM login URL.
    #
    # This resolves to:
    #
    #     /dashboard/login/
    #
    # through apps/crm/web_urls.py
    #

    response = redirect(
        "crm-login",
    )

    # =========================================================
    # DELETE CRM SESSION COOKIE
    # =========================================================
    #
    # This removes:
    #
    #     shvya_crm_sessionid
    #
    # from the browser.
    #

    delete_session_cookie(
        response,
        "dashboard",
    )

    # =========================================================
    # PREVENT DASHBOARD CACHING
    # =========================================================
    #
    # This is important after logout so that the browser does
    # not display a previously cached CRM dashboard when the
    # user navigates backward.
    #

    response["Cache-Control"] = (
        "no-cache, no-store, must-revalidate"
    )

    response["Pragma"] = "no-cache"
    response["Expires"] = "0"

    return response

    # ============================================================
# CRM FORGOT PASSWORD
# ============================================================


def crm_forgot_password_view(request):
    """
    Start the CRM password-reset flow.

    Security:
        - Does not reveal whether an email exists.
        - Only active organization users are eligible.
        - Superadmin users cannot use the CRM password reset.
        - A secure Django password-reset token is generated.
        - The reset link expires automatically when the password
          changes.
    """

    if request.method == "POST":

        email = (
            request.POST.get(
                "email",
                "",
            )
            .strip()
            .lower()
        )

        # --------------------------------------------------------
        # Find active organization CRM user.
        # --------------------------------------------------------

        user = (
            User.objects
            .filter(
                email__iexact=email,
                is_active=True,
                is_superuser=False,
                organization__isnull=False,
            )
            .first()
        )

        # --------------------------------------------------------
        # Always continue to the same success page.
        #
        # This prevents account enumeration.
        # --------------------------------------------------------

        if user is not None:

            uid = urlsafe_base64_encode(
                force_bytes(
                    user.pk
                )
            )

            token = default_token_generator.make_token(
                user
            )

            reset_url = request.build_absolute_uri(
                reverse(
                    "crm-password-reset",
                    kwargs={
                        "uidb64": uid,
                        "token": token,
                    },
                )
            )

            # ----------------------------------------------------
            # Email subject
            # ----------------------------------------------------

            subject = "Reset your SHVYA CRM password"

            # ----------------------------------------------------
            # Plain-text email
            # ----------------------------------------------------

            message = f"""
Hello,

We received a request to reset your SHVYA CRM password.

Click the link below to create a new password:

{reset_url}

This link can only be used while it remains valid.

If you did not request a password reset, you can safely ignore
this email.

Regards,
SHVYA AI
""".strip()

            # ----------------------------------------------------
            # Send email
            # ----------------------------------------------------

            try:

                send_mail(
                    subject=subject,
                    message=message,
                    from_email=getattr(
                        settings,
                        "DEFAULT_FROM_EMAIL",
                        None,
                    ),
                    recipient_list=[
                        user.email
                    ],
                    fail_silently=False,
                )

            except Exception:

                # Log the error but do not reveal whether the
                # account exists to the browser.
                import logging

                logging.getLogger(
                    __name__
                ).exception(
                    "CRM password reset email failed."
                )

        return redirect(
            "crm-password-reset-sent"
        )

    return render(
        request,
        "crm/forgot_password.html",
    )


# ============================================================
# CRM PASSWORD RESET EMAIL SENT
# ============================================================


def crm_password_reset_sent_view(request):
    """
    Confirmation page displayed after the forgot-password form.

    The page intentionally does not say whether the submitted
    email belongs to an existing account.
    """

    return render(
        request,
        "crm/password_reset_sent.html",
    )


# ============================================================
# CRM PASSWORD RESET
# ============================================================


def crm_password_reset_view(
    request,
    uidb64,
    token,
):
    """
    Validate a password-reset token and allow the user to
    choose a new password.
    """

    # --------------------------------------------------------
    # Decode user ID.
    # --------------------------------------------------------

    try:

        uid = force_str(
            urlsafe_base64_decode(
                uidb64
            )
        )

        user = User.objects.get(
            pk=uid
        )

    except (
        TypeError,
        ValueError,
        OverflowError,
        User.DoesNotExist,
    ):

        user = None

    # --------------------------------------------------------
    # Validate reset token.
    # --------------------------------------------------------

    valid_link = (
        user is not None
        and user.is_active
        and not user.is_superuser
        and user.organization_id is not None
        and default_token_generator.check_token(
            user,
            token,
        )
    )

    # --------------------------------------------------------
    # Invalid / expired token
    # --------------------------------------------------------

    if not valid_link:

        return render(
            request,
            "crm/password_reset_invalid.html",
            status=400,
        )

    # --------------------------------------------------------
    # POST — save new password
    # --------------------------------------------------------

    if request.method == "POST":

        form = SetPasswordForm(
            user,
            request.POST,
        )

        if form.is_valid():

            form.save()

            return redirect(
                "crm-password-reset-complete"
            )

    else:

        form = SetPasswordForm(
            user
        )

    return render(
        request,
        "crm/reset_password.html",
        {
            "form": form,
        },
    )


# ============================================================
# CRM PASSWORD RESET COMPLETE
# ============================================================


def crm_password_reset_complete_view(request):
    """
    Password reset successfully completed.
    """

    return render(
        request,
        "crm/password_reset_complete.html",
    )