# Generated by Django 6.1 on 2026-08-25 08:37

import apps.channels.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0007_pipeline_country_code_pipeline_owner_and_more'),
        ('organizations', '0004_organizationpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('api', 'Connect API'), ('hosted', 'Hosted Account')], default='api', max_length=10)),
                ('phone_number_id', models.CharField(blank=True, help_text='Meta WhatsApp phone_number_id used as the sender.', max_length=64)),
                ('waba_id', models.CharField(blank=True, help_text='Meta WhatsApp Business Account ID (for reference/lookup).', max_length=64)),
                ('display_phone_number', models.CharField(blank=True, max_length=32)),
                ('access_token', apps.channels.models.EncryptedTextField(blank=True, help_text='Meta system-user access token. Stored encrypted.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('failed', 'Failed'), ('disconnected', 'Disconnected')], default='pending', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to='organizations.organization')),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('from_number', models.CharField(max_length=32)),
                ('to_number', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='queued', max_length=15)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Full Meta payload for this message/status event.')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.whatsappaccount')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='channels_wh_organiz_18b21d_idx'), models.Index(fields=['lead', 'created_at'], name='channels_wh_lead_id_c70ee6_idx')],
            },
        ),
    ]