# Generated by Django 6.1 on 2026-08-26 10:39

import apps.channels.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0007_pipeline_country_code_pipeline_owner_and_more'),
        ('organizations', '0004_organizationpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('api', 'Connect API'), ('hosted', 'Hosted Account')], default='api', max_length=10)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('phone_number_id', models.CharField(blank=True, help_text='Meta WhatsApp phone_number_id used as the sender.', max_length=64)),
                ('waba_id', models.CharField(blank=True, help_text='Meta WhatsApp Business Account ID (for reference/lookup).', max_length=64)),
                ('display_phone_number', models.CharField(blank=True, max_length=32)),
                ('access_token', apps.channels.models.EncryptedTextField(blank=True, help_text='Meta system-user access token. Stored encrypted.')),
                ('welcome_message', models.TextField(blank=True, help_text="Auto-sent to a lead's first message on this number.")),
                ('request_contact_info', models.BooleanField(default=False, help_text='Ask the lead to share contact details before continuing.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('failed', 'Failed'), ('disconnected', 'Disconnected')], default='pending', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to='organizations.organization')),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkMessageCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('body', models.TextField(help_text='Free-form text. NOTE: Meta only allows free-form text to leads who messaged in the last 24 hours -- leads outside that window are skipped unless template_name is set.')),
                ('template_name', models.CharField(blank=True, help_text='Meta-approved template name, for leads outside the 24h window.', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_campaigns', to='organizations.organization')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_campaigns', to='crm.pipeline')),
                ('stage', models.ForeignKey(blank=True, help_text='Leave blank to target every stage in the pipeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_campaigns', to='crm.stage')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='channels.whatsappaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('from_number', models.CharField(max_length=32)),
                ('to_number', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='queued', max_length=15)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Full Meta payload for this message/status event.')),
                ('error', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.whatsappaccount')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='crm.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkMessageRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('skip_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='channels.bulkmessagecampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_bulk_recipients', to='crm.lead')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_recipient', to='channels.whatsappmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], default='marketing', max_length=20)),
                ('template_format', models.CharField(choices=[('standard', 'Standard Template'), ('carousel', 'Carousel Template')], default='standard', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused'), ('archived', 'Archived'), ('pending_deletion', 'Pending Deletion')], default='draft', max_length=20)),
                ('body', models.TextField(help_text='Use {{variable_name}} placeholders, e.g. {{lead_name}}.')),
                ('footer', models.CharField(blank=True, max_length=60)),
                ('attachment_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='none', max_length=10)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('meta_template_id', models.CharField(blank=True, max_length=128)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='channels.whatsappaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['organization', 'created_at'], name='channels_wh_organiz_18b21d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['lead', 'created_at'], name='channels_wh_lead_id_c70ee6_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulkmessagerecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'lead'), name='uniq_campaign_lead'),
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='uniq_account_template_name'),
        ),
    ]