# Generated by Django 6.1 on 2026-09-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='connection_type',
            field=models.CharField(choices=[('api', 'Connect API'), ('hosted', 'coexisted Account')], default='api', max_length=10),
        ),
    ]
