# Generated by Django 6.1 on 2026-08-26 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('organizations', '0004_organizationpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], default='marketing', max_length=20)),
                ('template_format', models.CharField(choices=[('standard', 'Standard Template'), ('carousel', 'Carousel Template')], default='standard', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused'), ('archived', 'Archived'), ('pending_deletion', 'Pending Deletion')], default='draft', max_length=20)),
                ('body', models.TextField(help_text='Use {{variable_name}} placeholders, e.g. {{lead_name}}.')),
                ('footer', models.CharField(blank=True, max_length=60)),
                ('attachment_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='none', max_length=10)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('meta_template_id', models.CharField(blank=True, max_length=128)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='channels.whatsappaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'name'), name='uniq_account_template_name')],
            },
        ),
    ]