# Generated by Django 6.1 on 2026-09-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_whatsappmessage_media_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='connection_type',
            field=models.CharField(choices=[('api', 'Connect API'), ('hosted', 'coexisted Account')], default='api', max_length=10),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='media_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Controlled outbound media transport data. Used for image, audio, video, and document messages.'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document')], default='text', help_text="WhatsApp content type for this message. URL messages remain type='text' and may use preview_url transport metadata.", max_length=15),
        ),
    ]
