# Generated by Django 6.1 on 2026-09-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_whatsappaccount_connection_type'),
        ('channels', '0005_alter_whatsappaccount_connection_type_and_more'),
    ]

    operations = [
    ]
