# Generated by Django 6.1 for SHVYA template management.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0007_whatsappconnectionattempt"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppTemplateMetadata",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("local_status", models.CharField(choices=[("draft", "Draft"), ("submitting", "Submitting"), ("submitted", "Submitted"), ("synced", "Synced"), ("sync_error", "Sync Error"), ("remote_deleted", "Not Found on Meta"), ("deleted", "Deleted")], db_index=True, default="draft", max_length=24)),
                ("language", models.CharField(default="en_US", max_length=16)),
                ("placeholder_mapping", models.JSONField(blank=True, default=dict)),
                ("components", models.JSONField(blank=True, default=list)),
                ("meta_response", models.JSONField(blank=True, default=dict)),
                ("meta_error_code", models.CharField(blank=True, max_length=64)),
                ("meta_error_subcode", models.CharField(blank=True, max_length=64)),
                ("meta_error_type", models.CharField(blank=True, max_length=128)),
                ("meta_error_message", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("template", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="meta_state", to="channels.whatsapptemplate")),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppTemplateOperation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("operation", models.CharField(choices=[("submit", "Submit"), ("sync", "Sync"), ("delete", "Delete"), ("copy", "Copy")], max_length=16)),
                ("success", models.BooleanField(default=False)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("meta_error_code", models.CharField(blank=True, max_length=64)),
                ("meta_error_subcode", models.CharField(blank=True, max_length=64)),
                ("meta_error_type", models.CharField(blank=True, max_length=128)),
                ("meta_error_message", models.TextField(blank=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="template_operations", to="channels.whatsappaccount")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="whatsapp_template_operations", to="organizations.organization")),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="operations", to="channels.whatsapptemplate")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="whatsapptemplatemetadata", index=models.Index(fields=["local_status", "last_synced_at"], name="wa_tpl_state_sync_idx")),
        migrations.AddIndex(model_name="whatsapptemplateoperation", index=models.Index(fields=["organization", "created_at"], name="wa_tpl_op_org_time_idx")),
        migrations.AddIndex(model_name="whatsapptemplateoperation", index=models.Index(fields=["template", "operation"], name="wa_tpl_op_tpl_kind_idx")),
    ]
