# Generated by Django 6.1 on 2026-09-07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0010_whatsapptemplatemetadata_carousel_config"),
        ("organizations", "0004_organizationpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostedChatIgnoreContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=32)),
                ("contact_name", models.CharField(blank=True, max_length=180)),
                ("chat_id", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ignored_existing_chats",
                        to="channels.whatsappaccount",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_chat_ignore_contacts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["contact_name", "phone_number"],
                "indexes": [
                    models.Index(
                        fields=["organization", "phone_number"],
                        name="hosted_ignore_org_phone_idx",
                    ),
                    models.Index(
                        fields=["account", "phone_number"],
                        name="hosted_ignore_acct_phone_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "phone_number"),
                        name="uniq_hosted_ignore_account_phone",
                    ),
                ],
            },
        ),
    ]
