# Generated by Django 6.1.1 on 2026-09-18 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0014_bulk_campaigns'),
        ('crm', '0026_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconversation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_conversations', to='crm.lead'),
        ),
    ]
