# Generated by Django 6.1 on 2026-10-02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0019_template_delivery_media"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppTemplateCTAEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("url", "Website"),
                            ("call", "Call"),
                            ("copy_code", "Copy code"),
                        ],
                        max_length=16,
                    ),
                ),
                ("button_index", models.PositiveSmallIntegerField()),
                (
                    "card_index",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("button_label", models.CharField(max_length=80)),
                ("destination", models.TextField(blank=True)),
                ("visitor_hash", models.CharField(max_length=64)),
                ("request_key", models.CharField(max_length=64, unique=True)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_cta_events",
                        to="channels.whatsappaccount",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_template_cta_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cta_events",
                        to="channels.whatsapptemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["template", "clicked_at"],
                        name="wa_cta_tpl_time_idx",
                    ),
                    models.Index(
                        fields=["account", "clicked_at"],
                        name="wa_cta_acct_time_idx",
                    ),
                    models.Index(
                        fields=["organization", "clicked_at"],
                        name="wa_cta_org_time_idx",
                    ),
                ],
            },
        ),
    ]
