# Generated by Django 6.1.1 on 2026-10-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0020_whatsapptemplatectaevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='is_operations_test',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
