"""Stable, customer-facing Vault schema. Keys are part of the agent API."""

SECTIONS = (
    {"key": "website", "title": "Website pages", "description": "Add the pages that explain your business best.", "guidance": "Share separate links for your homepage, products, pricing, About and Contact pages. Tell us about anything that is out of date.", "example": "Our services: https://example.com/services — prices are current.", "group": "Recommended"},
    {"key": "brochures", "title": "Brochures, catalogues & price lists", "description": "Give your team the documents customers need.", "guidance": "Upload brochures, menus, catalogues, policies and price lists. Explain each file and whether the AI may share it with customers.", "example": "2026 catalogue. Share when a customer asks about our product range.", "group": "Recommended"},
    {"key": "media", "title": "Photos & videos the AI can send", "description": "Show what you offer, with context for every file.", "guidance": "Upload product photos, walkthroughs or certificates. Describe what each file shows and when it should be sent.", "example": "A walkthrough of our Andheri branch. Share when someone asks to see the facilities.", "group": "Recommended"},
    {"key": "offerings", "title": "Products, services & pricing", "description": "Explain what you sell and how pricing works.", "guidance": "List services, products, packages, price ranges, minimum orders and delivery conditions. Say whether prices may be shared in chat.", "example": "Installation is included. Final quotations depend on the site survey.", "group": "Recommended"},
    {"key": "basics", "title": "Business basics", "description": "The practical details customers ask for.", "guidance": "Add branches, service areas, opening hours, timezone, holidays, contact details and booking or payment links.", "example": "Open Monday–Saturday, 10 am–7 pm, Asia/Kolkata. Closed Sunday.", "group": "Recommended"},
    {"key": "faqs", "title": "Questions customers ask & objections", "description": "Share real questions and the answers you want used.", "guidance": "Include common questions, concerns and objections, with answers your best salesperson would give.", "example": "Do you offer a trial? Yes, a 20-minute introductory session by appointment.", "group": "Recommended"},
    {"key": "team", "title": "Who handles leads", "description": "Tell us who should take over each conversation.", "guidance": "List names, roles, contact numbers, routing rules, fallback order and expected response times.", "example": "Product enquiries go to the sales team; service complaints go to the branch manager.", "group": "Recommended"},
    {"key": "qualification", "title": "Qualification", "description": "Define a good lead and the questions to ask.", "guidance": "Give 3–7 questions, their exact wording and options, qualifying criteria and deal-breakers. Include your typical sales cycle.", "example": "Which service are you interested in? What is your preferred start date?", "group": "Recommended"},
    {"key": "handoff", "title": "When the AI should hand over to a human", "description": "Set clear points for a person to step in.", "guidance": "Describe the situations, the message the AI should send, and the person or team that takes over.", "example": "If a customer asks for a custom discount, say our sales team will discuss the available options.", "group": "Recommended"},
    {"key": "blacklist", "title": "Topics the AI must never answer", "description": "Keep the conversation within your boundaries.", "guidance": "List restricted topics and explain whether the assistant should politely decline, ask for clarification or hand over.", "example": "Never promise guaranteed results or discuss another customer's personal information.", "group": "Recommended"},
    {"key": "rules", "title": "Tone, language & promises", "description": "Make the assistant sound like your business.", "guidance": "Include assistant name, tone, preferred languages and scripts, emoji preferences and promises it must never make.", "example": "Friendly, short replies. English and Hindi in Roman script. No guarantees about results.", "group": "Recommended"},
    {"key": "proof", "title": "Testimonials & proof", "description": "Share evidence customers are allowed to see.", "guidance": "Add approved customer quotes, case studies, awards and certifications, including attribution and context for numbers.", "example": "A customer-approved testimonial with their name and city.", "group": "If you have them"},
    {"key": "offers", "title": "Current offers", "description": "Explain each offer and when it ends.", "guidance": "Include the audience, start and expiry dates, terms, conditions and coupon code. Do not include expired offers as current.", "example": "New customers receive a free consultation until 31 December; appointment required.", "group": "If you have them"},
    {"key": "scripts", "title": "Sales scripts & past chats", "description": "Show conversations that reflect your style.", "guidance": "Share successful chats, calling scripts and email templates. Remove personal details that are not needed. These are style references.", "example": "Our opening call script and a redacted example of a successful follow-up.", "group": "If you have them"},
    {"key": "other", "title": "Anything else", "description": "Add anything we have not asked about.", "guidance": "Include seasonal changes, upcoming launches, useful context or follow-up ideas.", "example": "Our office will close for a local holiday; confirm dates before updating the assistant.", "group": "If you have them"},
)
SECTION_MAP = {section["key"]: section for section in SECTIONS}
SECTION_CHOICES = tuple((s["key"], s["title"]) for s in SECTIONS)
SECTION_KEYS = tuple(SECTION_MAP)
ORIGIN_CHOICES = (("fireflies", "Call transcript"), ("whatsapp", "WhatsApp"), ("ops_chat", "SHVYA team"), ("other", "Other"))
