# Generated by Django 6.1 on 2026-08-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Integration API Key', 'verbose_name_plural': 'Integration API Keys'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='can_upsert_leads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(default='temp', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
