# Generated by Django 6.1 on 2026-08-16 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_apikey_options_apikey_can_upsert_leads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='assigned_poc',
            field=models.ForeignKey(blank=True, help_text='Internal point of contact for this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poc_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='credits_alert_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='credits_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='credits_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='day_of_sale',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='operational_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to super admins.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='package',
            field=models.CharField(choices=[('diy', 'DIY'), ('dfy', 'DFY'), ('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='payment_mode',
            field=models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial (Installments)')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='renewal_payment_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total contract/invoice amount for this organization.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='organizations.organizationtag'),
        ),
    ]
