# Generated by Django 6.1 on 2026-09-23 10:14

from django.db import migrations, models


def migrate_pro(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Organization.objects.using(schema_editor.connection.alias).filter(package="pro").update(package="enterprise")


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_apikey_can_read_diagnostics'),
    ]

    operations = [
        migrations.RunPython(migrate_pro, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='package',
            field=models.CharField(choices=[('diy', 'DIY'), ('dfy', 'DFY'), ('free', 'Free'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
