# Generated by Django 6.1 on 2026-09-23 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDeletionCleanup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('files', models.JSONField(default=list)),
                ('hosted_session_ids', models.JSONField(default=list)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
